[package]
name = "pchat"
version = "0.0.0"
authors.workspace = true
publish = false
edition.workspace = true
default-run = "pchat"

[[bin]]
path = "src/main.rs"
name = "pchat"

[dependencies] 
clap =  { workspace = true}
tokio = { workspace = true}
futures = { workspace = true}
libp2p = { workspace = true}
libp2p-quic = { workspace = true}